/* FinPlan v1 — analytics/settings polish */
(() => {
  const $=(s,r=document)=>r.querySelector(s);
  const fa=()=>document.documentElement.lang==='fa';
  const copy=(en,faText)=>fa()?faText:en;
  const token=()=>localStorage.getItem('finplan-token');
  const api=async(path,options={})=>{const h=new Headers(options.headers||{});h.set('Authorization',`Bearer ${token()}`);if(options.body)h.set('Content-Type','application/json');const r=await fetch(path,{...options,headers:h});if(!r.ok)throw new Error(`API ${r.status}`);return r.json()};
  const money=v=>fa()?`${Number(v||0).toLocaleString('fa-IR')} ﷼`:`$${Number(v||0).toLocaleString('en-US')}`;
  function analytics(){const root=$('#transactionsWorkspace');if(!root)return;root.hidden=false;root.classList.add('visible');root.dataset.workspace='analytics';const month=localStorage.getItem('finplan-month')||new Date().toISOString().slice(0,7);root.innerHTML=`<div class="workspace-header"><div><span class="panel-label">${copy('ANALYTICS','تحلیل')}</span><h2>${copy('Financial insights','تحلیل مالی')}</h2></div><span class="panel-caption">${month}</span></div><div class="analytics-grid"><article class="workspace-card analytics-main" id="phaseAnalyticsMain"><div class="loading-state">Loading…</div></article><article class="workspace-card" id="phaseAnalyticsCategories"><div class="loading-state">Loading…</div></article></div>`;loadAnalytics(month)}
  async function loadAnalytics(month){try{const from=`${month}-01`,to=`${month}-31`;const [s,c,b]=await Promise.all([api(`/transactions/summary?from_date=${from}&to_date=${to}`),api(`/transactions/expenses-by-category?from_date=${from}&to_date=${to}`),api(`/budgets/summary?month=${month}`)]);const income=Number(s.total_income)||0,expense=Number(s.total_expense)||0,balance=Number(s.balance)||0;const ratio=income?Math.round(expense/income*100):0;const budget=Array.isArray(b)?b:[];const totalBudget=budget.reduce((n,x)=>n+Number(x.amount||0),0);$('#phaseAnalyticsMain').innerHTML=`<div class="analytics-heading"><div><span class="panel-label">${copy('SUMMARY','خلاصه')}</span><h3>${copy('This month','این ماه')}</h3></div><span class="analytics-balance ${balance<0?'negative':'positive'}">${money(balance)}</span></div><div class="analytics-stats"><div><span>${copy('Income','درآمد')}</span><strong>${money(income)}</strong></div><div><span>${copy('Expenses','هزینه‌ها')}</span><strong>${money(expense)}</strong></div><div><span>${copy('Transactions','تراکنش‌ها')}</span><strong>${s.transaction_count||0}</strong></div><div><span>${copy('Budget','بودجه')}</span><strong>${money(totalBudget)}</strong></div></div><div class="analytics-ratio"><span>${copy('Expense / income','نسبت هزینه به درآمد')}</span><b>${income?ratio+'%':'—'}</b><div class="workspace-progress"><span style="width:${Math.min(ratio,100)}%"></span></div></div>`;const entries=Object.entries(c||{}).sort((a,b)=>Number(b[1])-Number(a[1]));$('#phaseAnalyticsCategories').innerHTML=`<span class="panel-label">${copy('EXPENSE CATEGORIES','دسته‌بندی هزینه')}</span><h3>${copy('Where your money goes','هزینه‌ها کجا می‌روند')}</h3>${entries.map(([n,v])=>`<div class="category-bar"><div><span>${esc(n)}</span><b>${money(v)}</b></div><div class="workspace-progress"><span style="width:${expense?Math.min(Number(v)/expense*100,100):0}%"></span></div></div>`).join('')||`<div class="empty-state">${copy('No expense data yet.','هنوز داده‌ای برای هزینه‌ها نیست.')}</div>`)}catch(e){console.error(e);$('#phaseAnalyticsMain').innerHTML=`<div class="error-state">${copy('Analytics are unavailable.','تحلیل در دسترس نیست.')}</div>`}}
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
  function wire(){document.addEventListener('click',e=>{const n=e.target.closest('.nav-item[data-section="analytics"]');if(!n)return;e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('.nav-item[data-section]').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.main > section:not(#transactionsWorkspace)').forEach(x=>x.setAttribute('hidden','true'));analytics()},true)}
  document.addEventListener('DOMContentLoaded',wire);
})();