const API_BASE = window.FINPLAN_API_BASE || "http://127.0.0.1:8000";
let currentLanguage = localStorage.getItem("finplan-language") || "en";
let currentCurrency = localStorage.getItem("finplan-currency") || "USD";
let currentMonth = localStorage.getItem("finplan-month") || new Date().toISOString().slice(0, 7);
const translations={en:{dashboard:"Dashboard",transactions:"Transactions",budgets:"Budgets",analytics:"Analytics",settings:"Settings",personalFinance:"PERSONAL FINANCE",personalAccount:"Personal account",goodEvening:"Good evening",goodMorning:"Good morning",goodAfternoon:"Good afternoon",moneyMessage:"Here's what's happening with your money this month.",addTransaction:"Add transaction",totalIncome:"Total Income",totalExpenses:"Total Expenses",currentBalance:"Current Balance",budgetRemaining:"Budget Remaining",thisMonth:"this month",healthyBalance:"Healthy balance",used:"used",expenseOverview:"EXPENSE OVERVIEW",spendingThisMonth:"Spending this month",budget:"BUDGET",monthlyBudget:"Monthly budget",viewAll:"View all",totalBudget:"total budget",spent:"Spent",remaining:"Remaining",onTrack:"You're on track with your budget",budgetOverviewLabel:"BUDGETS",budgetOverview:"Budget overview",activity:"ACTIVITY",recentTransactions:"Recent transactions",monthPrompt:"Enter month (YYYY-MM):",invalidMonth:"Please enter a valid month like 2026-08.",transactionAdded:"Transaction added.",transactionFailed:"Could not add transaction.",noNotifications:"You're all caught up"},fa:{dashboard:"داشبورد",transactions:"تراکنش‌ها",budgets:"بودجه‌ها",analytics:"تحلیل",settings:"تنظیمات",personalFinance:"مدیریت مالی شخصی",personalAccount:"حساب شخصی",goodEvening:"عصر بخیر",goodMorning:"صبح بخیر",goodAfternoon:"بعدازظهر بخیر",moneyMessage:"وضعیت مالی این ماهت اینجاست.",addTransaction:"افزودن تراکنش",totalIncome:"کل درآمد",totalExpenses:"کل هزینه‌ها",currentBalance:"موجودی فعلی",budgetRemaining:"بودجه باقی‌مانده",thisMonth:"این ماه",healthyBalance:"موجودی سالم",used:"مصرف شده",expenseOverview:"نمای کلی هزینه‌ها",spendingThisMonth:"هزینه‌های این ماه",budget:"بودجه",monthlyBudget:"بودجه ماهانه",viewAll:"مشاهده همه",totalBudget:"کل بودجه",spent:"هزینه شده",remaining:"باقی‌مانده",onTrack:"وضعیت بودجه مناسب است",budgetOverviewLabel:"بودجه‌ها",budgetOverview:"نمای کلی بودجه",activity:"فعالیت",recentTransactions:"تراکنش‌های اخیر",monthPrompt:"ماه را وارد کن (YYYY-MM):",invalidMonth:"فرمت ماه صحیح نیست؛ مثل 2026-08 وارد کن.",transactionAdded:"تراکنش اضافه شد.",transactionFailed:"افزودن تراکنش ناموفق بود.",noNotifications:"اعلان جدیدی وجود ندارد"}};
function t(key){return translations[currentLanguage]?.[key]||translations.en[key]||key}
async function apiFetch(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const token=localStorage.getItem("finplan-token");if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API_BASE}${path}`,{...options,headers});if(response.status===401){localStorage.removeItem("finplan-token");localStorage.removeItem("finplan-user");location.reload();throw new Error("Unauthorized")}if(!response.ok)throw new Error(`API ${response.status}`);return response.json()}
function formatMoney(value){const amount=Number(value||0);return currentCurrency==="USD"?`$${amount.toLocaleString("en-US")}`:`${amount.toLocaleString("fa-IR")} ﷼`}
function updateMonthLabel(){const[y,m]=currentMonth.split("-").map(Number),label=document.querySelector("#monthLabel");if(label)label.textContent=new Intl.DateTimeFormat(currentLanguage==="fa"?"fa-IR":"en-US",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))}
function updateGreeting(){const hour=new Date().getHours(),key=hour<12?"goodMorning":hour<18?"goodAfternoon":"goodEvening",greeting=document.querySelector("#greeting");if(greeting)greeting.textContent=t(key)}
function setLanguage(language){currentLanguage=language==="fa"?"fa":"en";localStorage.setItem("finplan-language",currentLanguage);document.documentElement.lang=currentLanguage;document.documentElement.dir=currentLanguage==="fa"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(e=>{const key=e.dataset.i18n;if(translations[currentLanguage][key])e.textContent=translations[currentLanguage][key]});const button=document.querySelector("#languageSelector .language-current");if(button)button.textContent=currentLanguage.toUpperCase();updateMonthLabel();updateGreeting();window.dispatchEvent(new CustomEvent("finplan:language-change",{detail:currentLanguage}))}
function setCurrency(currency){currentCurrency=currency==="IRR"?"IRR":"USD";localStorage.setItem("finplan-currency",currentCurrency);const button=document.querySelector("#currencySelector .currency-current");if(button)button.textContent=currentCurrency;refreshDashboard();window.dispatchEvent(new CustomEvent("finplan:currency-change",{detail:currentCurrency}))}
function setDashboardValue(selector,value){document.querySelectorAll(`[data-dashboard="${selector}"]`).forEach(e=>e.textContent=typeof value==="number"?formatMoney(value):value)}
async function refreshDashboard(){try{const data=await apiFetch(`/dashboard?month=${encodeURIComponent(currentMonth)}`);setDashboardValue("income",data.income);setDashboardValue("expense",data.expense);setDashboardValue("balance",data.balance);setDashboardValue("budget-total",data.total_budget);setDashboardValue("budget-spent",data.budget_spent);setDashboardValue("budget-remaining",data.budget_remaining);setDashboardValue("budget-remaining-2",data.budget_remaining);document.querySelectorAll('[data-dashboard="budget-percentage"]').forEach(e=>e.textContent=`${data.budget_spent_percentage}%`);const progress=document.querySelector('[data-dashboard="progress"]');if(progress)progress.style.width=`${clamp(Number(data.budget_spent_percentage),0,100)}%`;const status=document.querySelector('[data-dashboard="budget-status"]');if(status)status.textContent=data.budget_status==="over_budget"?(currentLanguage==="fa"?"از بودجه عبور کرده‌ای":"You're over budget"):data.budget_status==="no_budget"?(currentLanguage==="fa"?"برای این ماه بودجه‌ای ثبت نشده":"No budget set for this month"):t("onTrack");await loadRecentTransactions();await loadBudgets();window.dispatchEvent(new CustomEvent("finplan:dashboard-refreshed",{detail:data}))}catch(error){console.error("FinPlan dashboard error:",error);document.querySelectorAll(".loading-state").forEach(e=>e.textContent=currentLanguage==="fa"?"اتصال به API برقرار نشد":"Could not connect to API")}}
async function loadRecentTransactions(){const list=document.querySelector("#transactionsList");if(!list)return;try{const items=await apiFetch(`/transactions?from_date=${currentMonth}-01&to_date=${currentMonth}-31`);list.innerHTML=items.slice(0,6).map(i=>`<div class="transaction-row"><div><strong>${escapeHTML(i.title)}</strong><span>${escapeHTML(i.category)}</span></div><strong class="${i.type==="income"?"positive":"negative"}">${i.type==="income"?"+":"-"}${formatMoney(i.amount)}</strong></div>`).join("")||`<div class="empty-state">${currentLanguage==="fa"?"تراکنشی برای این ماه نیست":"No transactions this month"}`; }catch{list.innerHTML=`<div class="empty-state">${currentLanguage==="fa"?"خطا در دریافت تراکنش‌ها":"Could not load transactions"}`}}
async function loadBudgets(){const list=document.querySelector("#budgetList");if(!list)return;try{const items=await apiFetch(`/budgets?month=${encodeURIComponent(currentMonth)}`);document.querySelector("#budgetCount")?.replaceChildren(document.createTextNode(`${items.length} ${currentLanguage==="fa"?"دسته":"categories"}`));list.innerHTML=items.map(i=>`<div class="budget-row"><span>${escapeHTML(i.category)}</span><strong>${formatMoney(i.amount)}</strong></div>`).join("")||`<div class="empty-state">${currentLanguage==="fa"?"بودجه‌ای ثبت نشده":"No budgets set"}` }catch{list.innerHTML=`<div class="empty-state">${currentLanguage==="fa"?"خطا در دریافت بودجه‌ها":"Could not load budgets"}`}}
function showWorkspace(section){const parts=[".dashboard-grid",".summary-grid",".budget-list-panel",".transactions-panel"];if(section==="dashboard"){parts.forEach(s=>document.querySelector(s)?.removeAttribute("hidden"));const w=document.querySelector("#transactionsWorkspace");if(w){w.classList.remove("visible");w.hidden=true;w.innerHTML="";delete w.dataset.workspace}}else{parts.forEach(s=>document.querySelector(s)?.setAttribute("hidden","true"));window.dispatchEvent(new CustomEvent("finplan:workspace",{detail:section}))}}
function setupControls(){document.querySelector("#languageSelector")?.addEventListener("click",()=>setLanguage(currentLanguage==="en"?"fa":"en"));document.querySelector("#currencySelector")?.addEventListener("click",()=>setCurrency(currentCurrency==="USD"?"IRR":"USD"));document.querySelector("#monthSelector")?.addEventListener("click",async()=>{const next=window.prompt(t("monthPrompt"),currentMonth);if(!next)return;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(next))return showToast(t("invalidMonth"));currentMonth=next;localStorage.setItem("finplan-month",currentMonth);updateMonthLabel();await refreshDashboard();window.dispatchEvent(new CustomEvent("finplan:month-change",{detail:currentMonth}))});document.querySelector("#notificationButton")?.addEventListener("click",()=>showToast(t("noNotifications")));document.querySelector("#viewTransactionsButton")?.addEventListener("click",()=>document.querySelector('.nav-item[data-section="transactions"]')?.click());document.querySelector("#viewBudgetsButton")?.addEventListener("click",()=>document.querySelector('.nav-item[data-section="budgets"]')?.click());document.querySelectorAll(".nav-item[data-section]").forEach(item=>item.addEventListener("click",event=>{event.preventDefault();document.querySelectorAll(".nav-item[data-section]").forEach(n=>n.classList.remove("active"));item.classList.add("active");const section=item.dataset.section;if(section==="settings"){showWorkspace(section);window.dispatchEvent(new CustomEvent("finplan:open-settings"));return}showWorkspace(section);if(section==="transactions")window.dispatchEvent(new CustomEvent("finplan:transactions-open"))}))}
function showToast(message){const toast=document.querySelector("#toast");if(!toast)return;toast.textContent=message;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2600)}
function clamp(v,min,max){return Math.min(Math.max(v,min),max)}
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
window.setLanguage=setLanguage;window.setCurrency=setCurrency;window.refreshDashboard=refreshDashboard;window.showToast=showToast;
async function initFinPlan(){setupControls();setLanguage(currentLanguage);updateMonthLabel();updateGreeting();await refreshDashboard()}
document.addEventListener("DOMContentLoaded",initFinPlan);