const API_BASE = window.FINPLAN_API_BASE || "";
let currentLanguage=localStorage.getItem("finplan-language")||"en";
let currentCurrency=localStorage.getItem("finplan-currency")||"USD";
let currentMonth=localStorage.getItem("finplan-month")||new Date().toISOString().slice(0,7);
const translations={en:{dashboard:"Dashboard",transactions:"Transactions",budgets:"Budgets",analytics:"Analytics",settings:"Settings",personalFinance:"PERSONAL FINANCE",personalAccount:"Personal account",goodEvening:"Good evening",goodMorning:"Good morning",goodAfternoon:"Good afternoon",moneyMessage:"Here's what's happening with your money this month.",addTransaction:"Add transaction",totalIncome:"Total Income",totalExpenses:"Total Expenses",currentBalance:"Current Balance",budgetRemaining:"Budget Remaining",thisMonth:"this month",healthyBalance:"Healthy balance",used:"used",expenseOverview:"EXPENSE OVERVIEW",spendingThisMonth:"Spending this month",budget:"BUDGET",monthlyBudget:"Monthly budget",viewAll:"View all",totalBudget:"total budget",spent:"Spent",remaining:"Remaining",onTrack:"You're on track with your budget",budgetOverviewLabel:"BUDGETS",budgetOverview:"Budget overview",activity:"ACTIVITY",recentTransactions:"Recent transactions",monthPrompt:"Enter month (YYYY-MM):",invalidMonth:"Please enter a valid month like 2026-08.",noNotifications:"You're all caught up"},fa:{dashboard:"داشبورد",transactions:"تراکنش‌ها",budgets:"بودجه‌ها",analytics:"تحلیل",settings:"تنظیمات",personalFinance:"مدیریت مالی شخصی",personalAccount:"حساب شخصی",goodEvening:"عصر بخیر",goodMorning:"صبح بخیر",goodAfternoon:"بعدازظهر بخیر",moneyMessage:"وضعیت مالی این ماهت اینجاست.",addTransaction:"افزودن تراکنش",totalIncome:"کل درآمد",totalExpenses:"کل هزینه‌ها",currentBalance:"موجودی فعلی",budgetRemaining:"بودجه باقی‌مانده",thisMonth:"این ماه",healthyBalance:"موجودی سالم",used:"مصرف شده",expenseOverview:"نمای کلی هزینه‌ها",spendingThisMonth:"هزینه‌های این ماه",budget:"بودجه",monthlyBudget:"بودجه ماهانه",viewAll:"مشاهده همه",totalBudget:"کل بودجه",spent:"هزینه شده",remaining:"باقی‌مانده",onTrack:"وضعیت بودجه مناسب است",budgetOverviewLabel:"بودجه‌ها",budgetOverview:"نمای کلی بودجه",activity:"فعالیت",recentTransactions:"تراکنش‌های اخیر",monthPrompt:"ماه را وارد کن (YYYY-MM):",invalidMonth:"فرمت ماه صحیح نیست؛ مثل 2026-08 وارد کن.",noNotifications:"اعلان جدیدی وجود ندارد"}};
function t(k){return translations[currentLanguage]?.[k]||translations.en[k]||k}
async function apiFetch(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};const token=localStorage.getItem("finplan-token");if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API_BASE}${path}`,{...options,headers});if(response.status===401){window.dispatchEvent(new CustomEvent("finplan:auth-required"));throw new Error("Unauthorized")}if(!response.ok)throw new Error(`API ${response.status}`);return response.json()}
function formatMoney(v){const n=Number(v||0);return currentCurrency==="USD"?`$${n.toLocaleString("en-US")}`:`${n.toLocaleString("fa-IR")} ﷼`}
function updateMonthLabel(){const[y,m]=currentMonth.split("-").map(Number),e=document.querySelector("#monthLabel");if(e)e.textContent=new Intl.DateTimeFormat(currentLanguage==="fa"?"fa-IR":"en-US",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))}
function updateGreeting(){const h=new Date().getHours(),k=h<12?"goodMorning":h<18?"goodAfternoon":"goodEvening",e=document.querySelector("#greeting");if(e)e.textContent=t(k)}
function setLanguage(l){currentLanguage=l==="fa"?"fa":"en";localStorage.setItem("finplan-language",currentLanguage);document.documentElement.lang=currentLanguage;document.documentElement.dir=currentLanguage==="fa"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(e=>{if(translations[currentLanguage][e.dataset.i18n])e.textContent=translations[currentLanguage][e.dataset.i18n]});const b=document.querySelector("#languageSelector .language-current");if(b)b.textContent=currentLanguage.toUpperCase();updateMonthLabel();updateGreeting();window.dispatchEvent(new CustomEvent("finplan:language-change",{detail:currentLanguage}))}
function setCurrency(c){currentCurrency=c==="IRR"?"IRR":"USD";localStorage.setItem("finplan-currency",currentCurrency);const b=document.querySelector("#currencySelector .currency-current");if(b)b.textContent=currentCurrency;if(localStorage.getItem("finplan-token"))refreshDashboard();window.dispatchEvent(new CustomEvent("finplan:currency-change",{detail:currentCurrency}))}
function setDashboardValue(s,v){document.querySelectorAll(`[data-dashboard="${s}"]`).forEach(e=>e.textContent=typeof v==="number"?formatMoney(v):v)}
async function refreshDashboard(){if(!localStorage.getItem("finplan-token"))return;try{const data=await apiFetch(`/dashboard?month=${encodeURIComponent(currentMonth)}`);setDashboardValue("income",data.income);setDashboardValue("expense",data.expense);setDashboardValue("balance",data.balance);setDashboardValue("budget-total",data.total_budget);setDashboardValue("budget-spent",data.budget_spent);setDashboardValue("budget-remaining",data.budget_remaining);setDashboardValue("budget-remaining-2",data.budget_remaining);document.querySelectorAll('[data-dashboard="budget-percentage"]').forEach(e=>e.textContent=`${data.budget_spent_percentage}%`);const p=document.querySelector('[data-dashboard="progress"]');if(p)p.style.width=`${Math.min(Math.max(Number(data.budget_spent_percentage),0),100)}%`;const s=document.querySelector('[data-dashboard="budget-status"]');if(s)s.textContent=data.budget_status==="over_budget"?(currentLanguage==="fa"?"از بودجه عبور کرده‌ای":"You're over budget"):data.budget_status==="no_budget"?(currentLanguage==="fa"?"برای این ماه بودجه‌ای ثبت نشده":"No budget set for this month"):t("onTrack");await loadRecentTransactions();await loadBudgets();window.dispatchEvent(new CustomEvent("finplan:dashboard-refreshed",{detail:data}))}catch(error){if(error.message!=="Unauthorized")console.error("FinPlan dashboard error:",error)}}
async function loadRecentTransactions(){const l=document.querySelector("#transactionsList");if(!l)return;try{const items=await apiFetch(`/transactions?from_date=${currentMonth}-01&to_date=${currentMonth}-31`);l.innerHTML=items.slice(0,6).map(i=>`<div class="transaction-row"><div><strong>${escapeHTML(i.title)}</strong><span>${escapeHTML(i.category)}</span></div><strong class="${i.type==="income"?"positive":"negative"}">${i.type==="income"?"+":"-"}${formatMoney(i.amount)}</strong></div>`).join("")||`<div class="empty-state">${currentLanguage==="fa"?"تراکنشی برای این ماه نیست":"No transactions this month"}</div>`}catch(error){if(error.message!=="Unauthorized")l.innerHTML=`<div class="empty-state">${currentLanguage==="fa"?"خطا در دریافت تراکنش‌ها":"Could not load transactions"}</div>`}}
async function loadBudgets(){const l=document.querySelector("#budgetList");if(!l)return;try{const items=await apiFetch(`/budgets?month=${encodeURIComponent(currentMonth)}`);document.querySelector("#budgetCount")?.replaceChildren(document.createTextNode(`${items.length} ${currentLanguage==="fa"?"دسته":"categories"}`));l.innerHTML=items.map(i=>`<div class="budget-row"><span>${escapeHTML(i.category)}</span><strong>${formatMoney(i.amount)}</strong></div>`).join("")||`<div class="empty-state">${currentLanguage==="fa"?"بودجه‌ای ثبت نشده":"No budgets set"}</div>`}catch(error){if(error.message!=="Unauthorized")l.innerHTML=`<div class="empty-state">${currentLanguage==="fa"?"خطا در دریافت بودجه‌ها":"Could not load budgets"}</div>`}}
function showWorkspace(s){const parts=[".dashboard-grid",".summary-grid",".budget-list-panel",".transactions-panel"];if(s==="dashboard"){parts.forEach(x=>document.querySelector(x)?.removeAttribute("hidden"));const w=document.querySelector("#transactionsWorkspace");if(w){w.hidden=true;w.classList.remove("visible");w.innerHTML="";delete w.dataset.workspace}}else{parts.forEach(x=>document.querySelector(x)?.setAttribute("hidden","true"));window.dispatchEvent(new CustomEvent("finplan:workspace",{detail:s}))}}
function setupControls(){document.querySelector("#languageSelector")?.addEventListener("click",()=>setLanguage(currentLanguage==="en"?"fa":"en"));document.querySelector("#currencySelector")?.addEventListener("click",()=>setCurrency(currentCurrency==="USD"?"IRR":"USD"));document.querySelector("#monthSelector")?.addEventListener("click",async()=>{const n=window.prompt(t("monthPrompt"),currentMonth);if(!n)return;if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(n))return showToast(t("invalidMonth"));currentMonth=n;localStorage.setItem("finplan-month",n);updateMonthLabel();if(localStorage.getItem("finplan-token"))await refreshDashboard();window.dispatchEvent(new CustomEvent("finplan:month-change",{detail:n}))});document.querySelector("#notificationButton")?.addEventListener("click",()=>showToast(t("noNotifications")));document.querySelector("#viewTransactionsButton")?.addEventListener("click",()=>document.querySelector('.nav-item[data-section="transactions"]')?.click());document.querySelector("#viewBudgetsButton")?.addEventListener("click",()=>document.querySelector('.nav-item[data-section="budgets"]')?.click());document.querySelectorAll(".nav-item[data-section]").forEach(i=>i.addEventListener("click",e=>{e.preventDefault();document.querySelectorAll(".nav-item[data-section]").forEach(n=>n.classList.remove("active"));i.classList.add("active");const s=i.dataset.section;showWorkspace(s);if(s==="settings")window.dispatchEvent(new CustomEvent("finplan:open-settings"));if(s==="transactions")window.dispatchEvent(new CustomEvent("finplan:transactions-open"))}))}
function showToast(m){const e=document.querySelector("#toast");if(!e)return;e.textContent=m;e.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>e.classList.remove("show"),2600)}
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
window.setLanguage=setLanguage;window.setCurrency=setCurrency;window.refreshDashboard=refreshDashboard;window.showToast=showToast;
function initFinPlan(){setupControls();setLanguage(currentLanguage);updateMonthLabel();updateGreeting()}
document.addEventListener("DOMContentLoaded",initFinPlan);