/* FinPlan v1 — Budgets & Analytics workspaces */
(() => {
    const API_BASE = window.FINPLAN_API_BASE || "http://127.0.0.1:8000";
    const state = { month: localStorage.getItem("finplan-month") || new Date().toISOString().slice(0,7), budgets: [], transactions: [], current: null };
    const $ = s => document.querySelector(s), fa = () => document.documentElement.lang === "fa";
    const esc = v => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
    const money = v => fa() ? `${Number(v||0).toLocaleString("fa-IR")} ﷼` : `$${Number(v||0).toLocaleString("en-US")}`;
    const toast = m => window.showToast?.(m);
    async function api(path, options = {}) {
        const token = localStorage.getItem("finplan-token");
        if (!token) throw new Error("Unauthorized");
        const headers = new Headers(options.headers || {}); headers.set("Content-Type","application/json"); headers.set("Authorization",`Bearer ${token}`);
        const r = await fetch(`${API_BASE}${path}`, {...options,headers});
        if (r.status === 401) { window.dispatchEvent(new CustomEvent("finplan:auth-required")); throw new Error("Unauthorized"); }
        if (!r.ok) throw new Error(`API ${r.status}`); return r.json();
    }
    function root(){return $("#transactionsWorkspace")}
    function mount(kind){const r=root();if(!r)return;state.current=kind;r.hidden=false;r.classList.add("visible");r.dataset.workspace=kind;if(kind==="budgets")renderBudgets(r);else if(kind==="analytics")renderAnalytics(r);}
    async function renderBudgets(r){r.innerHTML=`<div class="workspace-header"><div><span class="panel-label">${fa()?"بودجه":"BUDGETS"}</span><h2>${fa()?"مدیریت بودجه ماهانه":"Monthly budgets"}</h2></div><button class="primary-button workspace-add" id="addBudgetButton" type="button">＋ ${fa()?"افزودن بودجه":"Add budget"}</button></div><div class="workspace-grid" id="budgetWorkspaceGrid"><div class="loading-state">Loading…</div></div>`;try{const[budgets,summary]=await Promise.all([api(`/budgets?month=${encodeURIComponent(state.month)}`),api(`/budgets/summary?month=${encodeURIComponent(state.month)}`)]);state.budgets=budgets;const map=Object.fromEntries(summary.map(x=>[x.category,x]));$("#budgetWorkspaceGrid").innerHTML=budgets.map(b=>{const s=map[b.category]||{spent:0,remaining:b.amount,spent_percentage:0,status:"on_track"};return `<article class="workspace-card"><div class="workspace-card-top"><div><span class="panel-label">${esc(b.category)}</span><strong>${money(b.amount)}</strong></div><span class="workspace-status ${esc(s.status)}">${s.status==="over_budget"?(fa()?"عبور از بودجه":"Over budget"):s.status==="reached"?(fa()?"تکمیل":"Reached"):(fa()?"در مسیر":"On track")}</span></div><div class="workspace-progress"><span style="width:${Math.min(Math.max(Number(s.spent_percentage)||0,0),100)}%"></span></div><div class="workspace-card-meta"><span>${fa()?"مصرف":"Spent"} <b>${money(s.spent)}</b></span><span>${fa()?"باقی‌مانده":"Remaining"} <b>${money(s.remaining)}</b></span></div><div class="workspace-actions"><button type="button" data-edit-budget="${b.id}">${fa()?"ویرایش":"Edit"}</button><button type="button" data-delete-budget="${b.id}">${fa()?"حذف":"Delete"}</button></div></article>`}).join("")||`<div class="empty-state">${fa()?"برای این ماه بودجه‌ای ثبت نشده است.":"No budgets for this month yet."}</div>`;$("#addBudgetButton").onclick=addBudget;r.querySelectorAll("[data-delete-budget]").forEach(b=>b.onclick=()=>deleteBudget(b.dataset.deleteBudget));r.querySelectorAll("[data-edit-budget]").forEach(b=>b.onclick=()=>editBudget(b.dataset.editBudget));}catch(e){if(e.message!=="Unauthorized")console.error(e);$("#budgetWorkspaceGrid").innerHTML=`<div class="error-state">${fa()?"دریافت بودجه‌ها ناموفق بود.":"Could not load budgets."}</div>`}}
    async function addBudget(){const category=prompt(fa()?"دسته‌بندی بودجه:":"Budget category:","Food");if(!category?.trim())return;const amount=Number(prompt(fa()?"مبلغ بودجه:":"Budget amount:","1000"));if(!Number.isFinite(amount)||amount<=0)return;try{await api("/budgets",{method:"POST",body:JSON.stringify({category:category.trim(),amount:Math.round(amount),month:state.month})});toast(fa()?"بودجه اضافه شد.":"Budget added.");mount("budgets");await window.refreshDashboard?.()}catch(e){toast(e.message.includes("400")?(fa()?"این بودجه از قبل وجود دارد.":"A budget already exists for this category."):(fa()?"افزودن بودجه ناموفق بود.":"Could not add budget."))}}
    async function editBudget(id){const b=state.budgets.find(x=>String(x.id)===String(id));if(!b)return;const category=prompt(fa()?"دسته‌بندی:":"Category:",b.category);if(!category?.trim())return;const amount=Number(prompt(fa()?"مبلغ:":"Amount:",b.amount));if(!Number.isFinite(amount)||amount<=0)return;try{await api(`/budgets/${id}`,{method:"PUT",body:JSON.stringify({category:category.trim(),amount:Math.round(amount),month:state.month})});toast(fa()?"بودجه به‌روزرسانی شد.":"Budget updated.");mount("budgets");await window.refreshDashboard?.()}catch{toast(fa()?"به‌روزرسانی ناموفق بود.":"Could not update budget.")}}
    async function deleteBudget(id){if(!confirm(fa()?"این بودجه حذف شود؟":"Delete this budget?"))return;try{await api(`/budgets/${id}`,{method:"DELETE"});toast(fa()?"بودجه حذف شد.":"Budget deleted.");mount("budgets");await window.refreshDashboard?.()}catch{toast(fa()?"حذف ناموفق بود.":"Could not delete budget.")}}
    async function renderAnalytics(r){r.innerHTML=`<div class="workspace-header"><div><span class="panel-label">${fa()?"تحلیل":"ANALYTICS"}</span><h2>${fa()?"تحلیل مالی ماه":"Monthly analytics"}</h2></div><span class="panel-caption">${esc(state.month)}</span></div><div class="analytics-grid"><div class="workspace-card analytics-main" id="analyticsMain"><div class="loading-state">Loading…</div></div><div class="workspace-card" id="analyticsCategories"><div class="loading-state">Loading…</div></div></div>`;try{const from=`${state.month}-01`,to=`${state.month}-31`,[s,c]=await Promise.all([api(`/transactions/summary?from_date=${from}&to_date=${to}`),api(`/transactions/expenses-by-category?from_date=${from}&to_date=${to}`)]),total=Number(s.total_expense)||0,income=Number(s.total_income)||0,balance=Number(s.balance)||0;$("#analyticsMain").innerHTML=`<div class="analytics-heading"><div><span class="panel-label">${fa()?"خلاصه":"SUMMARY"}</span><h3>${fa()?"عملکرد این ماه":"This month's performance"}</h3></div><span class="analytics-balance ${balance<0?"negative":"positive"}">${money(balance)}</span></div><div class="analytics-stats"><div><span>${fa()?"درآمد":"Income"}</span><strong>${money(income)}</strong></div><div><span>${fa()?"هزینه‌ها":"Expenses"}</span><strong>${money(total)}</strong></div><div><span>${fa()?"تعداد تراکنش":"Transactions"}</span><strong>${s.transaction_count}</strong></div></div><div class="analytics-ratio"><span>${fa()?"نسبت هزینه به درآمد":"Expense / income"}</span><b>${income?`${Math.round(total/income*100)}%`:"—"}</b><div class="workspace-progress"><span style="width:${income?Math.min(total/income*100,100):0}%"></span></div></div>`;const entries=Object.entries(c).sort((a,b)=>b[1]-a[1]);$("#analyticsCategories").innerHTML=`<span class="panel-label">${fa()?"دسته‌بندی هزینه":"EXPENSE CATEGORIES"}</span><h3>${fa()?"بیشترین هزینه‌ها":"Where your money goes"}</h3><div class="category-bars">${entries.map(([n,v])=>`<div class="category-bar"><div><span>${esc(n)}</span><b>${money(v)}</b></div><div class="workspace-progress"><span style="width:${total?v/total*100:0}%"></span></div></div>`).join("")||`<div class="empty-state">${fa()?"داده‌ای برای تحلیل نیست.":"No expense data yet."}</div>`}</div>`}catch(e){if(e.message!=="Unauthorized")console.error(e);$("#analyticsMain").innerHTML=`<div class="error-state">${fa()?"تحلیل در دسترس نیست.":"Analytics are unavailable."}</div>`}}
    window.addEventListener("finplan:workspace",e=>mount(e.detail));
    window.addEventListener("finplan:month-change",e=>{state.month=e.detail;if(state.current)mount(state.current)});
})();